#!/bin/sh
php bin/console racv:ad-dd
php bin/console racv:insert:step2_1
php bin/console racv:update:step2_2
php bin/console racv:insert:step2_3
php bin/console racv:update:step2_4
php bin/console racv:update:step2_5
php bin/console racv:update:step2_6
php bin/console racv:update:step2_7
php bin/console racv:update:step2_8
