# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    date.helper:
        class: AppBundle\Utils\DateHelper

